### ISSUE TITLE
can't build on rust 1.11.0-nightly (a967611d8 2016-05-30)

### ISSUE THREAD

**Issue by Cynede** [mikedilger/textnonce#12]
> build.rs:20:35: 20:48 error: mismatched types [E0308]
> build.rs:20         ::serde_codegen::register(&mut registry);
>                                               ^~~~~~~~~~~~~
> build.rs:20:35: 20:48 help: run `rustc --explain E0308` to see a detailed explanation
> build.rs:20:35: 20:48 note: expected type `&mut syntex::Registry`
> build.rs:20:35: 20:48 note:    found type `&mut syntex::Registry`
> build.rs:20:35: 20:48 note: Perhaps two different versions of crate `syntex` are being used?
> build.rs:20         ::serde_codegen::register(&mut registry);
>                                               ^~~~~~~~~~~~~
> error: aborting due to previous error
> error: Could not compile `textnonce`.

**Comment by mikedilger** [comment]
Yep, the AST changes again.  Thanks.  I've pushed a new version 0.3.3 for use with syntex 0.33
