### ISSUE TITLE
Please push latest release code

### ISSUE THREAD

**Issue by scorphus** [mikedilger/textnonce#14]
Hello, @mikedilger!

I see you've published a new release, [`0.3.4`](https://crates.io/crates/textnonce/0.3.4), which defintely fixes issues with Syntex getting updated every once in a while – thanks for that – hence #13.

So, could you please push latest changes along with the `0.3.4` tag? Also, note I've already submitted a pull request to formdata: mikedilger/formdata#31 😉 I hope it's alright for a Rust newbie.

Thanks!

**Comment by mikedilger** [comment]
Sorry for that.  Pushed.
