### ISSUE TITLE
Remove unsafe block in function sized_configured

### ISSUE THREAD

**Issue by ZephOne** [mikedilger/textnonce#17]
Would it be possible to get rid of the unsafe block in the function sized_configured and use resize instead ? Is it important that spaces of the vector are not initialized before starting to write into the vector ? I am aware that the unsafe block is totally controlled, it's just to avoid presence of unsafe block.

**Comment by mikedilger** [comment]
I suppose the performance impact is almost always trivial, so I'd merge it if you submitted a PR.

**Comment by ZephOne** [comment]
Perfect, I got it on my machine. I fork and submit the PR
